# Generated by Django 3.2.9 on 2021-11-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211109_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='activity_id',
        ),
    ]
