# Generated by Django 3.2.9 on 2021-11-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_video_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.image'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.image'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.relationship'),
        ),
        migrations.AlterField(
            model_name='image',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.video'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='api.image'),
        ),
    ]
