# Generated by Django 3.2.9 on 2021-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211109_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
