# Generated by Django 3.2.9 on 2021-11-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='relationship',
        ),
        migrations.AddField(
            model_name='attribute',
            name='entities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='entities',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
