# Generated by Django 3.2.9 on 2021-12-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211110_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='custom', max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
